### ISSUE TITLE
panic: Can't open /etc/hosts

### ISSUE THREAD

**Issue by Karm** [intfeed/godns#2]
Hmm :-( Wat?

    panic: Can't open /etc/hosts
    
    goroutine 7 [running]:
    main.(*FileHosts).Refresh(0xc20801f740)
            /home/karm/go/src/github.com/Karm/godns/hosts.go:110 +0xf9
    main.func·001()
            /home/karm/go/src/github.com/Karm/godns/hosts.go:68 +0x40
    created by main.(*Hosts).refresh
            /home/karm/go/src/github.com/Karm/godns/hosts.go:74 +0xf5
    
    goroutine 1 [chan receive, 38 minutes]:
    main.main()
            /home/karm/go/src/github.com/Karm/godns/main.go:36 +0x294
    
    goroutine 5 [syscall, 39 minutes]:
    os/signal.loop()
            /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
    created by os/signal.init·1
            /usr/local/go/src/os/signal/signal_unix.go:27 +0x35
    
    goroutine 8 [syscall]:
    syscall.Syscall(0x2f, 0x4, 0xc2080889e8, 0x0, 0x23, 0x0, 0x0)
            /usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
    syscall.recvmsg(0x4, 0xc2080889e8, 0x0, 0x0, 0x0, 0x0)
            /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1933 +0x57
    syscall.Recvmsg(0x4, 0xc20d504000, 0xffff, 0xffff, 0xc20b9b47e0, 0x28, 0x28, 0x0, 0x433261, 0x0, ...)
            /usr/local/go/src/syscall/syscall_linux.go:519 +0x19b
    net.(*netFD).readMsg(0xc2080100e0, 0xc20d504000, 0xffff, 0xffff, 0xc20b9b47e0, 0x28, 0x28, 0x0, 0x0, 0x0, ...)
            /usr/local/go/src/net/fd_unix.go:292 +0x42b
    net.(*UDPConn).ReadMsgUDP(0xc20802e020, 0xc20d504000, 0xffff, 0xffff, 0xc20b9b47e0, 0x28, 0x28, 0xc2080a2a80, 0x7f668fdd6000, 0x418bd1, ...)
            /usr/local/go/src/net/udpsock_posix.go:96 +0x17f
    github.com/miekg/dns.ReadFromSessionUDP(0xc20802e020, 0xc20d504000, 0xffff, 0xffff, 0xffff, 0xffff, 0x0, 0x0)
            /home/karm/Projects/rob/go/src/github.com/miekg/dns/udp.go:44 +0xca
    github.com/miekg/dns.(*Server).readUDP(0xc2080a40e0, 0xc20802e020, 0x12a05f200, 0x0, 0x0, 0x0, 0x23, 0x0, 0x0)
            /home/karm/Projects/rob/go/src/github.com/miekg/dns/server.go:545 +0x14e
    github.com/miekg/dns.(*Server).serveUDP(0xc2080a40e0, 0xc20802e020, 0x0, 0x0)
            /home/karm/Projects/rob/go/src/github.com/miekg/dns/server.go:427 +0x114
    github.com/miekg/dns.(*Server).ListenAndServe(0xc2080a40e0, 0x0, 0x0)
            /home/karm/Projects/rob/go/src/github.com/miekg/dns/server.go:282 +0x7c7
    main.(*Server).start(0xc20800b6b0, 0xc2080a40e0)
            /home/karm/go/src/github.com/Karm/godns/server.go:52 +0x182
    created by main.(*Server).Run

**Comment by Karm** [comment]
@robcza @kozeltom ...weird :-/  Leaking FD and ulimits hit? Maybe. Investigating...

**Comment by Karm** [comment]
Might be fixed by https://github.com/intfeed/godns/pull/3 , to be tested.
